AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://zeeshan-nestedstack-bucket.s3.us-east-2.amazonaws.com/vpc.yaml'  

  EC2Stack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://zeeshan-nestedstack-bucket.s3.us-east-2.amazonaws.com/EC2.yaml' 
      Parameters:
        MyVPCId: !GetAtt VPCStack.Outputs.VPCId
        EC2MySubnetId1: !GetAtt VPCStack.Outputs.outputSubnetId1
        EC2MySubnetId2: !GetAtt VPCStack.Outputs.outputSubnetId2
        
  LoadBalancerStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://zeeshan-nestedstack-bucket.s3.us-east-2.amazonaws.com/Loadbalancer.yaml' 
      Parameters:
        MyVPCId: !GetAtt VPCStack.Outputs.VPCId
        EC2MySubnetId1: !GetAtt VPCStack.Outputs.outputSubnetId1
        EC2MySubnetId2: !GetAtt VPCStack.Outputs.outputSubnetId2
