AWSTemplateFormatVersion: 2010-09-09
Resources:
  NestedCall:
    Type: AWS::CloudFormation::Stack 
    Properties:
      TemplateURL: https://zeeshan-nbucket.s3.us-east-2.amazonaws.com/s3nested.yaml
      TimeoutInMinutes: 1
 
Outputs:
  StackRef:
    Value: !Ref NestedCall
  OutputFormNestedStack:
    Value: !GetAtt NestedCall.Outputs.BucketName         
